name: egyptian_supermaekat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  animated_text_kit: ^4.2.3
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^8.3.0
  go_router: ^16.0.0
  google_nav_bar: ^5.0.7
  google_sign_in: ^7.2.0
  injectable: ^2.5.2
  injectable_generator: ^2.9.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  lottie: ^3.3.1
  pinput: ^5.0.1
  retrofit: ^4.8.0
  retrofit_generator: ^10.1.1
  shared_preferences: ^2.5.3
  svg_flutter: ^0.0.1

dev_dependencies:
  build_runner: ^2.10.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf

    - family: Cairo-Medium
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf

    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

    - family: Cairo-SemiBold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
    - family: Aldhabi-Regular
      fonts:
        - asset: assets/fonts/Aldhabi-Regular.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null
